@ECHO OFF
SETLOCAL
CD %HOME%

FOR /F "usebackq" %%I IN (`dir /b %~dp0`) DO CALL :MAKE_LINK %%I

PAUSE
GOTO :EOF

:MAKE_LINK
  SET FILENAME=%~nx1
  SET SRCPATH=%~dp0%FILENAME%
  SET LINKPATH=%HOME%\%FILENAME%

  REM %HOME%にリンクを張る必要がないファイルを除外
  IF "%FILENAME%" == "install.bat" GOTO :EOF
  IF "%FILENAME%" == "README.md"   GOTO :EOF
  IF "%FILENAME%" == ".git"        GOTO :EOF
  IF "%FILENAME%" == ".gitmodules" GOTO :EOF

  REM すでにあるリンクを削除
  IF EXIST %LINKPATH%\ RMDIR /Q %LINKPATH%
  IF EXIST %LINKPATH%     DEL /Q %LINKPATH%
  IF ERRORLEVEL 1 GOTO :EOF

  REM リンク作成
  SET MKLINK_OPT=
  IF EXIST %SRCPATH%\ SET MKLINK_OPT=/D
  MKLINK %MKLINK_OPT% %LINKPATH% %SRCPATH%
GOTO :EOF
