[[plugins]] # Dein.vim
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ヘルプ
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''

[[plugins]] # color scheme
repo = 'w0ng/vim-hybrid'
hook_add = '''
  colorscheme hybrid
'''

[[plugins]] # cursor位置のコンテキストによってfiletypeを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # cursor位置のファイルタイプ判定ライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # TOML syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # yanktmp.vim
repo = 'rtakasuke/yanktmp.vim'
hook_add = '''
  let g:yanktmp_file = '/tmp/yanktmp'
  map <silent> sy :call YanktmpYank()<CR>
  map <silent> sp :call YanktmpPaste_p()<CR>
  map <silent> sP :call YanktmpPaste_P()<CR>
'''

[[plugins]] # vim-submode
repo = 'kana/vim-submode'
hook_add = '''
  " ウィンドウのサイズ変更をキーリピートできるようにする
  call submode#enter_with('winsize', 'n', '', '<C-w>>', '<C-w>>')
  call submode#enter_with('winsize', 'n', '', '<C-w><', '<C-w><')
  call submode#enter_with('winsize', 'n', '', '<C-w>+', '<C-w>+')
  call submode#enter_with('winsize', 'n', '', '<C-w>-', '<C-w>-')
  call submode#map('winsize', 'n', '', '>', '<C-w>>')
  call submode#map('winsize', 'n', '', '<', '<C-w><')
  call submode#map('winsize', 'n', '', '+', '<C-w>+')
  call submode#map('winsize', 'n', '', '-', '<C-w>-')
  " タブページの切り替えをキーリピートできるようにする
  call submode#enter_with('tabchange', 'n', '', 'gt', 'gt')
  call submode#enter_with('tabchange', 'n', '', 'gT', 'gT')
  call submode#map('tabchange', 'n', '', 't', 'gt')
  call submode#map('tabchange', 'n', '', 'T', 'gT')
'''

[[plugins]] # Github issue
repo = 'jaxbot/github-issues.vim'
on_cmd = 'Gissue'
hook_add = '''
  let g:github_issues_no_omni = 1
'''

[[plugins]] # Unite
repo = 'Shougo/unite.vim'
depends = ['vimproc.vim']
on_cmd = 'Unite'
hook_add = '''
  let g:unite_split_rule = 'botright'
  let g:unite_enable_start_insert = 0
  let g:unite_enable_short_source_names = 1
  let g:unite_source_menu_menus = {}
  " unite-grepのバックエンドをptに切り替える
  " http://qiita.com/items/c8962f9325a5433dc50d
  let g:unite_source_grep_encoding = 'utf-8'
  if executable('pt')
    let g:unite_source_grep_command = 'pt'
    let g:unite_source_grep_default_opts = '--nocolor --nogroup'
    let g:unite_source_grep_recursive_opt = ''
    let g:unite_source_grep_max_candidates = 200
  endif
  autocmd FileType unite call s:unite_my_settings()
  function! s:unite_my_settings()
    " <ESC>連打で終了
    nmap <buffer> <ESC>   <Plug>(unite_exit)
    imap <buffer> <ESC><ESC>   <Plug>(unite_exit)
    " Ctrl+J/Kで選択
    imap <buffer> <C-j>   <Plug>(unite_select_next_line)
    imap <buffer> <C-k>   <Plug>(unite_select_previous_line)
    " 1ワード削除(インサートモードと同じ挙動になるようにする)
    nmap <buffer> <C-w>   <Plug>(unite_delete_backspace_word)
    " 既に入力されている文字を削除した状態で入力
    nmap <buffer> I       <Plug>(unite_append_end)<Plug>(unite_delete_backward_line)
    nmap <buffer> <C-u>   <Plug>(unite_append_end)<Plug>(unite_delete_backward_line)
  endfunction
  nnoremap [unite] <Nop>
  nmap <Space> [unite]
  " 前回のUnite結果を再表示
  nnoremap <silent> [unite]<Space> :<C-u>UniteResume<CR>
  " ソースを選択
  nnoremap <silent> [unite]s :<C-u>Unite source<CR>
  " カレントディレクトリ配下のファイルを表示
  nnoremap <silent> [unite]f :<C-u>Unite
        \ -start-insert -hide-source-names
        \ file_rec file/new<CR>
  " git管理のファイルを表示
  nnoremap <silent> <C-p> :<C-u>Unite
        \ -start-insert -hide-source-names
        \ file_rec/git:--cached:--others:--exclude-standard
        \ file/new<CR>
  " Grep
  nnoremap <silent> [unite]g :<C-u>Unite grep:. -no-empty<CR>
'''

[[plugins]] # vimproc.vim
repo = 'Shougo/vimproc.vim'
lazy = 1
build = 'make'

[[plugins]] # Vimfiler
repo = 'Shougo/vimfiler.vim'
hook_add = '''
  let g:vimfiler_as_default_explorer = 1
'''

[[plugins]] # :Gwrite, :Gdiff, :GcommitなどGで始まるコマンドを提供
repo = 'tpope/vim-fugitive'
hook_add = '''
  command! Gci Gcommit
  command! Gcia Gcommit -a
'''

[[plugins]] # gitの差分を左端に表示する
repo = 'airblade/vim-gitgutter'

[[plugins]] # :Agitでgitのログを見る
repo = 'cohama/agit.vim'

[[plugins]] # Gist操作
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
hook_add = '''
  let g:gista#command#list#default_opener = 'botright 15 split'
  let g:gista#command#post#default_public = 0
  autocmd FileType gista-list call s:gista_list_mappings()
  function! s:gista_list_mappings()
    nmap <buffer> <ESC> <Plug>(gista-quit)
  endfunction
'''

[[plugins]] # Gist操作(Uniteプラグイン)
repo = 'lambdalisue/vim-gista-unite'
depends = ['vim-gista']

[[plugins]] # emmet-vim
repo = 'mattn/emmet-vim'
on_ft = ['html']
hook_add = '''
  let g:user_emmet_leader_key = '<c-y>'
'''

[[plugins]] # QuickRun
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
  let g:quickrun_config = {
              \ 'ruby': { 'command': 'bundruby' }
              \ }
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
depends = ['vim-anzu', 'vim-asterisk', 'incsearch.vim']
on_map = '<Plug>'
hook_add = '''
  set ignorecase
  set smartcase
  set hlsearch
  let g:incsearch#auto_nohlsearch = 1
  map /  <Plug>(incsearch-forward)
  map ?  <Plug>(incsearch-backward)
  map g/ <Plug>(incsearch-stay)
  map n  <Plug>(incsearch-nohl-n)<Plug>(anzu-update-search-status)
  map N  <Plug>(incsearch-nohl-N)<Plug>(anzu-update-search-status)
  map *  <Plug>(incsearch-nohl0)<Plug>(asterisk-z*)<Plug>(anzu-update-search-status)
  map #  <Plug>(incsearch-nohl0)<Plug>(asterisk-z#)<Plug>(anzu-update-search-status)
  map g* <Plug>(incsearch-nohl0)<Plug>(asterisk-gz*)<Plug>(anzu-update-search-status)
  map g# <Plug>(incsearch-nohl0)<Plug>(asterisk-gz#)<Plug>(anzu-update-search-status)
  augroup vim-anzu
    " カーソルが移動したとき(CursorMoved)、一定時間キー入力がないとき(CursorHold,CursorHoldI)、
    " ウインドウを移動したとき(WinLeave)、タブを移動したとき(TabLeave)に
    " 検索ヒット数の表示を消去する
    autocmd!
    autocmd CursorMoved,CursorHold,CursorHoldI,WinLeave,TabLeave *
          \ call anzu#clear_search_status()
  augroup END
'''
[[plugins]]
repo = 'osyo-manga/vim-anzu'
lazy = 1
[[plugins]]
repo = 'haya14busa/vim-asterisk'
lazy = 1

[[plugins]] # ステータスライン強化
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive']
hook_add = '''
  let g:lightline = {
        \ 'active': {
        \   'left': [
        \     ['mode', 'paste'],
        \     ['readonly', 'filename', 'modified'],
        \     ['gitbranch'],
        \     ['anzu'],
        \   ],
        \   'right': [
        \     ['rowinfo'],
        \     ['fileformat', 'fileencoding', 'filetype'],
        \   ],
        \ },
        \ 'inactive': {
        \   'left':  [ ['filename', 'modified'] ],
        \   'right': [ ['rowinfo'] ],
        \ },
        \ 'component': {
        \   'anzu': '%{anzu#search_status()}',
        \   'gitbranch': '%{fugitive#statusline()}',
        \   'rowinfo': '%4l/%L(%3p%%):%-3v',
        \ },
        \ 'subseparator': {'left': '', 'right': '|'},
        \ }
  command! -bar LightlineUpdate
        \ call lightline#init() |
        \ call lightline#colorscheme() |
        \ call lightline#update()
'''

[[plugins]]
repo = 'renumber.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vital.vim'
lazy = 1

[[plugins]]
repo = 'lambdalisue/vital-Web-API-GitHub'
lazy = 1
