#! /usr/bin/env bash
# kill unused popup session

escape_tmux_formats() {
  local text=$(cat)
  text=$(echo "$text" | sed "s/#[^{]/.*/g")
  while echo "$text" | grep -q '#{[^#{}]*}'; do
    text=$(echo "$text" | sed "s/#{[^#{}]*}/.*/g")
  done
  echo $text
}

pattern=$(
  tmux show-options -gv '@toggle-popup-session-name-format' |
    sed -e 's/[][)(\\.*^$+?|]/\\&/g' |
    escape_tmux_formats
)
this_session=$(tmux display-message -pF '#S')

diff --old-line-format='' --unchanged-line-format='' --new-line-format='%L' \
  <(tmux list-panes -aF '#{E:@toggle-popup-session-name-format}' | uniq) \
  <(tmux list-sessions -F '#S' -f "#{m/r:${pattern},#S}") |
  xargs -I {} tmux kill-session -t {}
