#!/usr/bin/env zsh

ghq_root=$(ghq root)
for ghq_path in $(ghq list | grep -E "$*"); do
  (
    cd $ghq_root/$ghq_path

    status_msg=$(git status --short)
    [[ $? != 0 || 1 -lt $(wc -l <<< "$status_msg") ]]
    status_ret=$?

    log_msg=$(git log --branches --not --remotes --oneline --graph --decorate --color=always)
    [[ $? != 0 || -n "$log_msg" ]]
    log_ret=$?

    if [[ $status_ret = 0 || $log_ret = 0 ]]; then
      echo "\e[1;34m> $ghq_path\e[0m"
      git -c status.color=always status --branch --short
      if [[ $log_ret = 0 ]]; then
        echo "$log_msg"
      fi
    fi
  )
done
