[tools]
# Github
github-cli = "latest"
hub = "latest"

# CLI Tools
ghq = "latest"
fzf = "latest"
jq = "latest"
delta = "latest"    # better diff
bat = "latest"      # better cat
ripgrep = "latest"  # better grep
fd = "latest"       # better find

# Editor
neovim = "latest"

# Language
node = "latest"

# Automatically added
