[tools]
# Github
github-cli = "latest"
hub = "latest"

# CLI Tools
ghq = "latest"
fzf = "latest"
jq = "latest"
delta = "latest"    # better diff
bat = "latest"      # better cat
ripgrep = "latest"  # better grep
fd = "latest"       # better find
lazygit = "latest"  # git TUI client

# Editor
neovim = "latest"

# nodejs
node = "latest"
pnpm = "latest"
yarn = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@google/clasp" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@antfu/ni" = "latest" # npm/pnpm/yarn package manager
"npm:@sasazame/ccresume" = "latest" # claude-code resume

# python
python = "latest"
uv = "latest"
